### ISSUE TITLE
[BUG] `AssertionError` on jpg5.su

### ISSUE THREAD

**Issue by baccccccc** [jbsparrow/CyberDropDownloader#607]
### I have taken steps to troubleshoot my issue first

- [x] I'm using the latest version of `cyberdrop-dl-patched`
- [x] I’ve read the wiki and my issue isn’t already covered.
- [x] I’ve checked existing issues to ensure this hasn’t been reported already.

### Describe the bug

here's a few jpg5.su albums that result in `AssertionError` during scrape
```
"https://jpg5.su/a/bc-071524.YgYy5K/?sort=title_asc&page=1","See Log for Details",""
"https://jpg5.su/a/bianca.YmDZkm","See Log for Details",""
"https://jpg5.su/a/bianca-censori-2025-grammy-awards-ai-watermark-removal.YwU1t9","See Log for Details",""
```

here's an example trace
```
                    ERROR    Scrape Failed: https://jpg5.su/a/bc-071524.YgYy5K/?sort=title_asc&page=1 ()                                                                                                                            logger.py:27
                             ╭──────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────────────────╮             
                             │ C:\Users\[REDACTED]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\utils\utilities.py:41 in wrapper           │             
                             │                                                                                                                                                                                                    │             
                             │    38 │   │   link = item if isinstance(item, URL) else item.url                                                                                                                                   │             
                             │    39 │   │   origin = exc_info = None                                                                                                                                                             │             
                             │    40 │   │   try:                                                                                                                                                                                 │             
                             │ ❱  41 │   │   │   return await func(self, *args, **kwargs)                                                                                                                                         │             
                             │    42 │   │   except CDLBaseError as e:                                                                                                                                                            │             
                             │    43 │   │   │   log_message_short = e_ui_failure = e.ui_message                                                                                                                                  │             
                             │    44 │   │   │   log_message = f"{e.ui_message} - {e.message}" if e.ui_message != e.message                                                                                                       │             
                             │       else e.message                                                                                                                                                                               │             
                             │                                                                                                                                                                                                    │             
                             │ C:\Users\[REDACTED]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\scraper\crawlers\chevereto_crawler.py:173  │             
                             │ in album                                                                                                                                                                                           │             
                             │                                                                                                                                                                                                    │             
                             │   170 │   │   │   new_scrape_item = self.create_scrape_item(scrape_item, link)                                                                                                                     │             
                             │   171 │   │   │   self.manager.task_group.create_task(self.run(new_scrape_item))                                                                                                                   │             
                             │   172 │   │                                                                                                                                                                                        │             
                             │ ❱ 173 │   │   async for soup in self.web_pager(scrape_item):                                                                                                                                       │             
                             │   174 │   │   │   links = soup.select(self.album_img_selector)                                                                                                                                     │             
                             │   175 │   │   │   for link in links:                                                                                                                                                               │             
                             │   176 │   │   │   │   link_str: str = link.get("src")                                                                                                                                              │             
                             │                                                                                                                                                                                                    │             
                             │ C:\Users\[REDACTED]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\scraper\crawlers\chevereto_crawler.py:278  │             
                             │ in web_pager                                                                                                                                                                                       │             
                             │                                                                                                                                                                                                    │             
                             │   275 │   │   │   if not next_page:                                                                                                                                                                │             
                             │   276 │   │   │   │   break                                                                                                                                                                        │             
                             │   277 │   │   │   page_url_str: str = next_page.get("href")                                                                                                                                        │             
                             │ ❱ 278 │   │   │   page_url = self.parse_url(page_url_str)                                                                                                                                          │             
                             │   279 │                                                                                                                                                                                            │             
                             │   280 │   @staticmethod                                                                                                                                                                            │             
                             │   281 │   async def get_sort_by_new_url(url: URL) -> URL:                                                                                                                                          │             
                             │                                                                                                                                                                                                    │             
                             │ C:\Users\[REDACTED]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\scraper\crawler.py:256 in parse_url        │             
                             │                                                                                                                                                                                                    │             
                             │   253 │   │   scrape_item.add_to_parent_title(title)                                                                                                                                               │             
                             │   254 │                                                                                                                                                                                            │             
                             │   255 │   def parse_url(self, link_str: str, relative_to: URL | None = None) -> URL:                                                                                                               │             
                             │ ❱ 256 │   │   assert link_str                                                                                                                                                                      │             
                             │   257 │   │   assert isinstance(link_str, str)                                                                                                                                                     │             
                             │   258 │   │   encoded = "%" in link_str                                                                                                                                                            │             
                             │   259 │   │   base = relative_to or self.primary_base_domain                                                                                                                                       │             
                             ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯             
                             AssertionError                                                                                                                                                                                                     
```

### Desired result

should work, or at least provide a more meaningful error in `Scrape_Error_URLs.csv`.

### Steps to help reproduce the behavior

see above

### Relevant logs

see above

### Operating system/environment

Windows 11, version 24H2

### Python Version

3.13.752.0

### Cyberdrop-DL version

6.4.0

**Comment by NTFSvolume** [comment]
- Fixed by #606

**Comment by crazydavebacon** [comment]
Hey. The fix was done with my Post #599 a few days ago. When will there be an update so its implemented?

**Comment by jbsparrow** [comment]
It should be released in a few days.

**Comment by baccccccc** [comment]
did the fix make it to 6.5.0?

I still see this even after the upgrade.

**Comment by NTFSvolume** [comment]
There's no release with the fix yet. It will be included in v6.6.0
